# Generated by Django 4.0.2 on 2022-02-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_device', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enviroment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_humidity', models.CharField(max_length=30)),
                ('air_humidity', models.CharField(max_length=30)),
                ('temperature', models.CharField(max_length=30)),
                ('date_now', models.DateTimeField()),
            ],
        ),
    ]
