# Generated by Django 4.0.2 on 2022-02-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housefts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviroment',
            name='altitude',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AddField(
            model_name='enviroment',
            name='pressure',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='enviroment',
            name='air_humidity',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='enviroment',
            name='ground_humidity',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
        migrations.AlterField(
            model_name='enviroment',
            name='temperature',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
    ]
